### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Cupnfish** [rgripper/rusty-bomber#1]
It’s been a busy couple of days, and after that we started trying bevy.

I am a rookie in game development, please advise me. :smile:

**Comment by rgripper** [comment]
@Cupnfish  Same here, haha. This is an attempt to build the dumbest version of Bomberman up to a version where you can win by entering a portal hidden in on of the wall blocks. 
So far I've implemented collision logic. Next is monsters, then death from collision with monsters. Then blowing up monsters and destructable walls. then game winning condition.
It's all mostly game logic stuff and discovering Bevy API for this one.
Next mini-project would be a biome-related game logic piece (e.g. Minecraft-like biome logic with growing trees, in 2D)

**Comment by zuiyu1998** [comment]
I want to join you. How can we contact you?

**Comment by Cupnfish** [comment]
> 
> 
> I want to join you. How can we contact you?

My question, should leave the relevant contact information, when I decide to use and contact everyone, will inform you. At present I am doing this project summary, therefore will not open next project temporarily, waits for us to be ready will inform you.

**Comment by zuiyu1998** [comment]
> > I want to join you. How can we contact you?
> 
> My question, should leave the relevant contact information, when I decide to use and contact everyone, will inform you. At present I am doing this project summary, therefore will not open next project temporarily, waits for us to be ready will inform you.

好的，我的邮箱是1542844298@qq.com。
