### ISSUE TITLE
Can't see the game picture at rgripper.github.io/rusty-bomber/ 

### ISSUE THREAD

**Issue by xuxucode** [rgripper/rusty-bomber#16]
I am interested in this project, how can I try it?
![image](https://user-images.githubusercontent.com/8274162/106220478-8da2ee80-6216-11eb-8bd2-10e100875354.png)

**Comment by Cupnfish** [comment]
You can try this: https://github.com/rgripper/rusty-bomber/releases/tag/1.0

**Comment by Cupnfish** [comment]
The reason why the pictures cannot be seen is due to network reasons. Our game is deployed on github's page service, and the game is not optimized for loading assets, Sometimes there is a weird situation where you can see the main body of the game but there is no picture.

**Comment by xuxucode** [comment]
Thanks, I got it work by building native release, so much fun!
